# list of languages for which language servers are started; choose from:
#   al               bash             clojure          cpp              csharp           csharp_omnisharp
#   dart             elixir           elm              erlang           fortran          go
#   haskell          java             julia            kotlin           lua              markdown
#   nix              perl             php              python           python_jedi      r
#   rego             ruby             ruby_solargraph  rust             scala            swift
#   terraform        typescript       typescript_vts   yaml             zig
languages:
- python

# the encoding used by text files in the project
encoding: "utf-8"

# whether to use the project's gitignore file to ignore files
ignore_all_files_in_gitignore: true

# list of additional paths to ignore
ignored_paths: []

# whether the project is in read-only mode
read_only: false

# list of tool names to exclude
excluded_tools: []

# initial prompt for the project
initial_prompt: ""

project_name: "omni-search-engine"
included_optional_tools: []
